services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: user_orders_db
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: qwER!234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_db -d user_orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    ports:
      - "8000:8000"
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy